// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import("element-plus/es")["ElTable"]
    ElTableV2: typeof import("element-plus/es")["ElTableV2"]
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"]
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"]
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"]
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"]
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"]
    SprintForm: typeof import('./src/components/SprintForm.vue')['default']
    SprintItem: typeof import('./src/components/SprintItem.vue')['default']
    SprintList: typeof import('./src/components/SprintList.vue')['default']
    TeammateForm: typeof import("./src/components/TeammateForm.vue")["default"]
    TeammateItem: typeof import("./src/components/TeammateItem.vue")["default"]
    TeammateList: typeof import("./src/components/TeammateList.vue")["default"]
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"]
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"]
  }
}
